### ISSUE TITLE
익헨에 milk force라고 그룹으로 검색하면 삭제된 작품이 1개뜨는데

### ISSUE THREAD

**Issue by jaejunghan** [dc-koromo/koromo-copy#1]
여기서는 검색이 안되네요. 404로 삭제된 작품도 검색 할수 없나요

**Comment by dc-koromo** [comment]
현재 베타 버전에선 검색이 불가능함을 확인했습니다

그리고 artistcg는 보통 n/a로 분류되니 '설정->다운로더->히토미->데이터 최적화 사용'을 끄고 재시작 후 다시 찾아보세요

그래도 안된다면 번호를 직접 검색해보세요
