### ISSUE TITLE
프로그램을 켜고 검색을 하면 오류가 발생해요

### ISSUE THREAD

**Issue by azf1664** [dc-koromo/koromo-copy#10]
![제목 없음](https://user-images.githubusercontent.com/51169720/58572380-86c01d80-8276-11e9-8f23-d0d36f41fd11.png)
첨부파일처럼 오류가 발생하고 프로그램이 꺼지네요.
며칠 전까지는 잘 사용했었어요...

**Comment by dc-koromo** [comment]
관리자권한으로 실행해보세요

**Comment by azf1664** [comment]
​
관리자 권한으로 실행해도 recent:0-25를 검색하면 똑같이 꺼져요...
-----Original Message-----

**Comment by dc-koromo** [comment]
DPI 프로그램을 사용해도 문제가 해결되지 않는다면 VPN을 이용하실 수 밖에 없을 것 같아요

**Comment by azf1664** [comment]
컴퓨터를 포맷하고 다시 실행해보니 이젠 exe 파일을 눌러도 아무 반응이 없네요... 기존의 방법처럼 exe 파일을 다운받은 채로 독립된 폴더에 넣어서 실행해도 아무런 반응이 없고, 관리자 권한으로 실행해도 응답이 없으니 답답하네요... 다른 파일들은 다 잘 되는데...
