### ISSUE TITLE
다운로드 넘버링과 미리보기

### ISSUE THREAD

**Issue by prostfone** [dc-koromo/koromo-copy#11]
만화를 다운로드 할 시에 넘버링이 뒤죽박죽이 됩니다.
똑같은 파일을 다운로드 할 때마다 사진의 넘버링이 바뀝니다. (7쪽이 넘버링 002 였는데 재다운로드시 013으로 바뀌는 등)
페이지 쪽수의 순서가 무작위로 배열되고 앞표지와 뒷표지가 중간에 끼어있는 등의 문제가 발생합니다.
또한 미리보기의 이미지가 오랫동안 로딩되지 않는데 이것은 인터넷의 문제인가요?

**Comment by dc-koromo** [comment]
익헨 다운로더에 넘버링이 잘못되는 문제가 있어 고쳤습니다. https://github.com/dc-koromo/koromo-copy/commit/e026469a5bbd708179523e945de7add74d808a7e

이미지가 로딩되지 않는 문제는 크게 두가지 원인이 있습니다.
다운로드가 느리거나 다운로드가 중간에 끊겨 표시되지 않는 경우가 있고,
이미 다운로드된 이미지가 메모리에서 지워져 사라지는 경우가 있습니다.
후자의 경우엔 수정중에 있습니다.

**Comment by prostfone** [comment]
그럼 수정하신 부분은 어떻게 해야 적용할 수 있나요
제가 직접 컴파일링해야 되나요??

**Comment by dc-koromo** [comment]
https://github.com/dc-koromo/koromo-copy/releases/tag/1.10.7095.35925 여기서 다운로드해주세여

**Comment by prostfone** [comment]
확실히 베타 버전이라 약간 불안정한 감이 있군요.

![캡처2](https://user-images.githubusercontent.com/51329755/58986292-0f5f3080-8818-11e9-9399-3655204e92eb.PNG)

다음은 일반적으로 실행했을 때에 다운로드 하려하면 뜨는 에러 메시지입니다. 직후 바로 프로그램이 종료됩니다.

![캡처](https://user-images.githubusercontent.com/51329755/58986427-50efdb80-8818-11e9-9a86-853be5ad1713.PNG)

관리자 권한으로 실행하면 다운로드는 할 수 있고 정상적으로 성공했으나 이런 에러 메시지가 뜹니다.

**Comment by dc-koromo** [comment]
아 실수했네요
수정했으니 확인부탁드려요
https://github.com/dc-koromo/koromo-copy/releases/tag/1.10.7096.18990

2019년 6월 6일 (목) 오전 5:02, prostfone <notifications@github.com>님이 작성:

**Comment by prostfone** [comment]
으음.... 아예 삭제하고 새로 주신 주소로 다시 받았지만 오류는 그대로입니다
![캡처3](https://user-images.githubusercontent.com/51329755/59041950-91049c00-88b4-11e9-98a3-4a86f49cdf76.PNG)

**Comment by prostfone** [comment]
음... 계속 7095버전으로 뜨네요...

**Comment by dc-koromo** [comment]
수정했습니다 재확인 부탁드려요
https://github.com/dc-koromo/koromo-copy/releases/download/1.10.7096.18990/Koromo.Copy.UX.exe

2019년 6월 6일 (목) 오후 11:59, prostfone <notifications@github.com>님이 작성:

**Comment by prostfone** [comment]
![캡처4](https://user-images.githubusercontent.com/51329755/59081501-66a0f600-8929-11e9-90b9-d965160c7adf.PNG)
버전 업데이트는 정상적으로 표기됩니다.
그러나 이 오류가 뜨는 이유는 왜일까요...

**Comment by dc-koromo** [comment]
어떤 상황에서 다운로드가 안되는건지 알 수 있을 까요?
어떤 검색어로 검색했고 어떤 작품을 다운로드하려했는지요

**Comment by prostfone** [comment]
음...
답변을 보고 방금 여러 검색어를 시도해 보았습니다.
charater:zelda, series:one_punch_man, series:one_piece, series:naruto 등등...

모두선택하고 다운로드 하는 경우 아예 다운로드 로딩 표시조차 뜨지않고 장문의 오류가 발생합니다.
![캡처5](https://user-images.githubusercontent.com/51329755/59116650-02148400-8987-11e9-97f2-12b6d6d3d4eb.PNG)


하나 또는 두 개 선택시 '불안정한 작업 진행중' 이라는 로딩표시 이후 아래와 같은 오류가 뜹니다.
![캡처4](https://user-images.githubusercontent.com/51329755/59116681-135d9080-8987-11e9-9628-7fa6fc4bf629.PNG)


혹시라도 작품이 필요하실까봐 몇몇 예를 남겨드립니다만은 십수번 시도해본 결과 모든 작품이 오류가 뜨는 것 같습니다.

 character:hinata_hyuga - Attaka Uzumaki
 series:one_punch_man - ONE - HURRICANE 1
                                        ONE - HURRICANE 2
                                        ONE - HURRICANE 3
                                .
                                .
                                .
                                        ONE - HURRICANE 6
character:boa_hancock - MEROMERO GIRLS NEW WORLD

**Comment by dc-koromo** [comment]
https://github.com/dc-koromo/koromo-copy/releases/download/1.10.7098.18059/Koromo.Copy.UX.exe
확인해 주세요

2019년 6월 8일 (토) 오전 12:51, prostfone <notifications@github.com>님이 작성:

**Comment by prostfone** [comment]
확인헀습니다.
해결되었습니다. 감사합니다
