### ISSUE TITLE
CLI 인터페이스 제공 계획에 관해.

### ISSUE THREAD

**Issue by affinityDrops** [dc-koromo/koromo-copy#12]
Console 기능을 CLI로 제공하실 계획이 있으신가요?

감사합니다.

**Comment by dc-koromo** [comment]
왜 CLI 프로그램이 필요한거죠?

**Comment by affinityDrops** [comment]
개인적으로 간단한 형태의 분류기를 만들었는데 CLI가 제공된다면 다른 것도 할 수 있을거 같아서요. e-archive 에 단 이슈도 같은 맥락이에요. 지금은 'hitomi_downloader' 의 메타데이터로 검색하는데 좀 한계가 있어서...
