### ISSUE TITLE
저장폴더에 {Date}  토큰 쓰면 다운로드 버튼 누를때 에러 납니다.

### ISSUE THREAD

**Issue by KiwiCube** [dc-koromo/koromo-copy#14]
.\\{Date}\\[{Artists}] {id} {Title} 식으로 저장하려고 하는데, {Date} 토큰만 쓰면 셋팅에서 저장은 되는데, 다운로드 누르면 폴더 작성부분에서 에러가 나네요..

Version 1.11.7111.39906 (x64) 입니다.

**Comment by dc-koromo** [comment]
커밋: https://github.com/dc-koromo/koromo-copy/commit/297a5c6f65425bb6ef19cbe696413da74d79aaf8
릴리즈: https://github.com/dc-koromo/koromo-copy/releases/tag/1.11.7112.32840

아래 릴리즈 주소에서 수정된 프로그램 받을 수 있어요
확인해 주세요

**Comment by KiwiCube** [comment]
> 커밋: [297a5c6](https://github.com/dc-koromo/koromo-copy/commit/297a5c6f65425bb6ef19cbe696413da74d79aaf8)
> 릴리즈: https://github.com/dc-koromo/koromo-copy/releases/tag/1.11.7112.32840
> 
> 아래 릴리즈 주소에서 수정된 프로그램 받을 수 있어요
> 확인해 주세요

네. 확인 되었습니다.  감사합니다. 그런데 폴더에서 만들어지는 날짜가 "오늘" 날짜네요. "Uploaded" 날짜인줄 알았는데, 그게 맞는게 아닌가 싶기도 합니다. 아니면 "UploadedDate" 같은 토큰을 넣으면 어떻까요
감사합니다.
