### ISSUE TITLE
어늘날부터 갑자기 이런 에러가 계속 생기면서 업데이트를 해도 작동을 안합니다

### ISSUE THREAD

**Issue by danggle** [dc-koromo/koromo-copy#15]
![제목 없음1](https://user-images.githubusercontent.com/16499084/59976694-17361780-9603-11e9-8634-20d3197ba85b.png)

원인..이 뭘까요?

윈도우10 홈버전 최신 업데이트 다했습니다

**Comment by danggle** [comment]
아..물론 dpi 키고도이러네요

**Comment by dc-koromo** [comment]
https://hitomi.la/
히토미 웹사이트 접속되는지 확인해주세요

**Comment by danggle** [comment]
아 sk라 vpn켜야만 들어가져요
