### ISSUE TITLE
[의견] 익헨 아카이브 자동 다운로드 지원

### ISSUE THREAD

**Issue by whatohyou** [dc-koromo/koromo-copy#16]
익헨의 경우 보면 오른쪽에 아카이브 다운로드 기능이 있고,
클릭하면 오리지널 자료 혹은 x1280으로 리샘플된 자료를 받을 수가 있습니다.
오리지널 자료는 보관하기에 너무 크므로 오리지널을 받아서 1280으로 리샘플하게 되면 매일 업데이트 받으면 하드디스크를 많이 읽어서 수명이 단축됩니다.
그래서 리셈플된 자료들을 자동으로 아카이브로 다운로드하려고 합니다.

프로그램 폴더에 주소목록 glink.txt에 주소를 쭈욱 넣어놓으면,
프로그램이 자동으로 그 주소들에서 (디폴트)리샘플된 자료만 다운로드를 실행하고 성공한 것들은 목록에서 삭제하고 실패한 것들은 남겨둬서 확인할 수 있도록 해주면 편할 것 같습니다.

일단 그러한 내용을 제가 만든 프로그램에 업데이트 하고 있습니다.
그리고 작가의 경우에는 다운로드한 작가는 +3점, 다운로드 하지 않고 넘긴 작가는 -1점을 주어서 데이터를 모아서 자동으로 점수가 낮은 작가는 필터링 하도록 데이터를 모으고 있습니다.
그리고 작가들의 이미지 겔러리의 경우에는 반복되어 올라오는 경우가 많으므로 신규 이미지 업데이트가 전체 용량의 33%를 넘지 않으면 필터링해서 보이지 않고 제거하도록 하고 있습니다.

**Comment by dc-koromo** [comment]
해당 기능을 추가해서 기능이나 성능상으로 얻을 수 있는 이점이 뭐죠?
히토미에서 다운로드할 수 있는 것을 굳이 익헨가서 다운로드하지 않아요
익헨주소만 알고있을때를 위해 익헨 다운로더를 추가해달라는 의미인가요?
