### ISSUE TITLE
고해상도 모니터에서 UI가 흐려집니다.

### ISSUE THREAD

**Issue by LulinPollux** [dc-koromo/koromo-copy#17]
배율이 100%를 넘는 모니터에서 프로그램을 실행하면 UI가 흐리게 보입니다.
메인 윈도우만 흐리게 보이고 다른 도구 및 유틸리티의 창은 괜찮습니다.
그런데 최대화를 하면 정상적으로 보여요.

지금 고쳐보려고 이것저것 수정해보고 있는데, 잘 안되네요.
혹시 고쳐주실 수 있나요?

**Comment by dc-koromo** [comment]
https://github.com/dc-koromo/koromo-copy/releases/tag/1.11.7136.17361
이 바이너리에서도 같은 문제가 발생하는지 확인해주세요

**Comment by LulinPollux** [comment]
빠른 답변 감사합니다.
이슈가 오히려 더 심해졌어요... 이전 릴리즈에서는 정상적이던 UI 컴포넌트까지 흐려졌습니다.
원인을 찾던 중에 [assembly: DisableDpiAwareness] 코드가 추가된 것을 확인했습니다.
테스트 프로그램에 위 코드를 적용해보니까 모든 컴포넌트가 흐려지네요.

이 문제는 크게 중요한 문제는 아니고 제 생각엔 고치는데 시간이 오래 걸릴 것으로 보입니다.
다른 것 먼저 개발하시고 천천히 해결하셔도 괜찮습니다.

**Comment by LulinPollux** [comment]
아, 방금 test-highresolution-monitor 브랜치로 빌드해보니까 고쳐졌어요!
감사합니다.

**Comment by dc-koromo** [comment]
test-highresolution-monitor로 고쳐진거면 WindowChrome 쪽 문제같네요
제가 고해상도 모니터를 사용하는게 아니라서 프로그램을 고쳐도 확인할 방법이 없어요
저도 이것저것 만져보고 있긴한데 아마 빠른시일내에 고치는건 어려울 것 같아요
