### ISSUE TITLE
이헨도 자료검색이 가능한가요?

### ISSUE THREAD

**Issue by elakwmq1** [dc-koromo/koromo-copy#19]
c94 자료들 다운받고싶은데 히토미는 자료 이름에 c94 같은것이 없고 제목만 있다보니 
검색해도 나오질 않네요.  설명페이지 3.다운로더 지원 목록을 보면 e-hentai도 지원이 되던데
검색을 하는 방법이 따로 있나요?

ps. 파일 300권정도를 다운로드를 하고 놔뒀는데 이런 오류 메세지가 뜨는데 어떤 이유로 뜨는 건가요? 메세지가 뜬상태인데 다운로드는 진행이 되고 있습니다.
---------------------------
Koromo Copy 1.12.7148.1227
---------------------------
프로그램 내부에서 예외처리되지 않은 오류가 발생했습니다. 오류가 계속된다면 개발자에게 문의하십시오. mscorlib
StackTrace:    위치: System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   위치: System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   위치: System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)

   위치: Koromo_Copy.Component.Hitomi.HitomiJson.Save() 파일 C:\Tools\koromo-copy\Koromo Copy\Component\Hitomi\HitomiJson.cs:줄 51

   위치: Koromo_Copy_UX.DownloadSpace.Instance_CompleteGroup(Object sender, Tuple`2 e)

   위치: Koromo_Copy.Net.DownloadGroup.downloadCallback(String url, String filename, Object obj) 파일 C:\Tools\koromo-copy\Koromo Copy\Net\DownloadGroup.cs:줄 100

   위치: Koromo_Copy.Net.EmiliaQueue.remote_download_thread_handler(Object i) 파일 C:\Tools\koromo-copy\Koromo Copy\Net\EmiliaQueue.cs:줄 329

   위치: System.Threading.ThreadHelper.ThreadStart_Context(Object state)

   위치: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   위치: System.Threading.ThreadHelper.ThreadStart(Object obj)
---------------------------
확인   
---------------------------

**Comment by dc-koromo** [comment]
기존 데이터 Original Title를 넣으면 메타데이터 크기가 너무 커지니 독립된 검색도구로 추가할께요

**Comment by dc-koromo** [comment]
https://github.com/dc-koromo/koromo-copy/commit/96a7d9ae1109d9776046c860dce9cf8c595a3e8e
해당 설정을 추가했습니다
다음 버전부터 사용가능합니다
