### ISSUE TITLE
다운로드 되는 작품의 폴더명 변경에 관하여

### ISSUE THREAD

**Issue by nikin78** [dc-koromo/koromo-copy#20]
다운로드 되는 폴더명의 기본 양식은

[{Id}] {Title}

이와 같이 알고 있는데, 이를 

{(id)} {[artist]}{[group]} {title} {[lang][series]}
(번호, 작가, 그룹 제목 언어 시리즈)

이와 같이 바꾸고 싶으나, 내장된 히토미 탐색기 도구를 이용해 설정하더라도

번호와 제목을 제외하면 작가의 경우 달리 표기가 안되고 그냥 Aritst라고만 써지는 등

순서를 제외하곤 반영이 되지 않은 것 같습니다.

현재 Koromo 다운로더에서는 이와 같은 기능을 구현하는 것이 불가능한 상태인지,

아니면 제가 달리 미처 헤아리지 못한 부분이 있는지 문의드립니다.

**Comment by KiwiCube** [comment]
{artists} => s가 더 들어갑니다.

**Comment by dc-koromo** [comment]
조만간 범용성있는 문법을 설계해서 적용해볼께요
