### ISSUE TITLE
현재 히토미 모든언어 설정 시 검색이 안 되는 것 같습니다

### ISSUE THREAD

**Issue by nikin78** [dc-koromo/koromo-copy#21]
단일 단어로 설정하면 정상적으로 검색이 되나,

모든 언어로 설정 시 검색을 해도 장시간 반응이 없는데,

데이터양이 너무 많아 결과 출력이 안되는 거라 생각해서

작품수가 모든 언어 합쳐서 5개 밖에 안되는 작가를 골라 검색해도

여전히 검색 결과 출력이 안되네요...

**Comment by dc-koromo** [comment]
런타임때 언어를 바꾸려면 "다운로더->히토미->데이터 최적화 사용" 옵션이 꺼져있어야 합니다.
옵션을 계속사용하려면 언어를 바꾼후 프로그램을 재시작해주세요
그래도 안된다면 어떤 작가를 검색했을때 안되었는지 알려주세요
