### ISSUE TITLE
최근 히토미에 업로드된 일부 항목이 노출되지 않는 문제

### ISSUE THREAD

**Issue by EDD1802** [dc-koromo/koromo-copy#22]
안녕하세요 언제나 프로그램 잘 이용하고 있습니다. 
낮은 빈도이긴 하나 간혹 한두개의 작품이 프로그램에서 검색되지 않는 문제가 있는 듯 합니다.
https://hitomi.la/galleries/1457301.html
예전에도 몇 번씩 발견한적 있었는데 일단 최근 작품 중에서는 위 항목이 그러한듯 합니다.
어떤 원인인지 해결이 가능할까요??

**Comment by dc-koromo** [comment]
히토미 측에서 자료를 늦게 미러링해 발생한 문제로 보입니다
데이터 동기화시 최신 작품 번호기준 +-2000개를 스캔하는데 거기에 포함되지 않는 작품이라면 발견되지 않을 수 있습니다
가끔가다가 146만개(이미 있는거제외)를 전부다 스캔할 때도있으니 나중에라도 추가 되긴합니다
지금 1400000부터 1465346까지 스캔했으니, 동기화하면 정상적으로 보일겁니다
