### ISSUE TITLE
다운받는도중 에러메시지

### ISSUE THREAD

**Issue by hangle7** [dc-koromo/koromo-copy#25]
Cannot find '숫자'! This item was not found in Hiyobi, Ex-Hentai, and Hitomi. Contact to the developer.
Run program as an administrator, or use a DPI program or VPN
이래뜨는건 어찌해야하나요??

**Comment by dc-koromo** [comment]
두 번째 줄에 나와있네요
프로그램을 관리자 권한으로 실행하던가, DPI 프로그램을 사용하던가 VPN을 이용하세요
