### ISSUE TITLE
수동으로 데이터를 업데이트해도 업데이트가 되지 않습니다.

### ISSUE THREAD

**Issue by kkookko12** [dc-koromo/koromo-copy#26]
설명서에 있는 방법대로 메타데이터와 히든데이터를 새로 덮어쓰고 run gbt - 시작 - 합치기 - test 8 과정을 거친 후에 프로그램을 다시 켜서 데이터를 불러와도 그대로 9월 1일 이후로는 업데이트가 되어있지 않습니다. 혹시 더 자세한 설명이 가능하시면 부탁드려요!

**Comment by pss757** [comment]
![image](https://user-images.githubusercontent.com/36108469/64415699-c6e23800-d0d0-11e9-810e-4703cf47d696.png)

**Comment by affinityDrops** [comment]
메뉴얼에 나온대로 `hitomi -test 8` 가 끝난 후 앱을 재시작을 하면 데이터 동기화가 완료된 상태입니다. 더이상 "설정"에서 하시면 안됩니다.

앱 재시작 후에 "설정" 에서 동기화 버튼을 누르셨는지 확인해보세요. 이제 "설정" 탭에서 하는 동기화는 제대로 작동하지 않습니다.

덧붙여서  gallery block tester 창에서 "시작", "끝"에 들어갈 번호가 새로운 갤러리가 있는지 찾으려는 범위입니다. 프로그램이 자동으로 정해주기도 하지만 본인이 생각하기에 누락된 갤러리가 있다면 직접 조정하셔야 할 겁니다.
