### ISSUE TITLE
다운로드가 되지 않습니다

### ISSUE THREAD

**Issue by kkookko12** [dc-koromo/koromo-copy#29]
그동안 감사하게도 수동으로 업데이트를 해서 잘 받고 있었습니다.
그런데 어제부터 갑자기 다운로드가 되지 않습니다.
vpn을 바꿔도 똑같고 read me 2에 있는대로 timeout 등등의 설정을 바꿔도 0kb에서 다운로드가 시작되지 않아요
정말 가끔 될 때도 있는데 20쪽 정도 다운을 받고 나면 갑자기 0으로 돌아오더니 다운로드가 되지 않습니다.
정말 답답하네요..
참고로 검색은 아주 잘 됩니다.

**Comment by rumen-scholar** [comment]
개발자님 및 다른 개발관련 이해가 있으신 분을 위해 첨언하자면....
다운로드시 콘솔창에서 원격서버 사용할수 없음이 반환되고있습니다.
해당 url 들이 막힌것 같은데....
변경할수 있는 법을 알려주신다면 도움이 될 것 같습니다.

**Comment by dc-koromo** [comment]
https://github.com/dc-koromo/koromo-copy/releases/tag/1.16.7214.18757x64
