### ISSUE TITLE
히토미 다운로드 경로 설정시 "유효하지 않은 경로입니다." 문제

### ISSUE THREAD

**Issue by eufo** [dc-koromo/koromo-copy#3]
경로 설정시  백슬래시 바로 뒤에 일반 문자와 토큰을 혼용하면 "유효하지 않은 경로입니다." 경고 메세지 뜨며 경로 설정이 안됩니다. hitomi copy에서는 의도대로 잘 동작하던 기능입니다

여기 게시판이 백슬래시 문자 표기가 안되는 것 같아서 예시는 스크린샷 첨부합니다

![1](https://user-images.githubusercontent.com/45713258/49687039-928d1b80-fb40-11e8-9e32-ceebd8586e46.jpg)

**Comment by dc-koromo** [comment]
https://github.com/dc-koromo/koromo-copy/commit/15d6984809f713a82a89526a40901ff2830892c5
수정했습니다
