### ISSUE TITLE
11-03 version install error

### ISSUE THREAD

**Issue by hashback1** [dc-koromo/koromo-copy#4]
![Screenshot_20191104-113152_Package installer](https://user-images.githubusercontent.com/57169674/68096881-16898800-fef7-11e9-8847-24a41fac168f.jpg)

10-22 version successful install

Only 11-03 version has this issue

**Comment by dc-koromo** [comment]
Try again.
I replaced a new version that fixes installing bug.

**Comment by hashback1** [comment]
> Try again.
> I replaced a new version that fixes installing bug.

Thx
