### ISSUE TITLE
실행해도 무반응인데 혹시 무슨 문제인지 아시나요?

### ISSUE THREAD

**Issue by SC1100** [dc-koromo/koromo-copy#5]
내용 그대로 실행해도 반응이 없어요.....
히토미 카피 쓰다가 오류발생 경로 : 메타데이터 다운로더  이런식으로 나와서 코로모 다운로더 쓰려고 하는데 더블클릭해도 아무 반응이 없네요 혹시 해결방법 아시나요?
그리고 프로그램 잘 쓰고 있습니다 항상 감사합니다

**Comment by dc-koromo** [comment]
새로운 폴더를 만들고, 그 폴더에 https://github.com/dc-koromo/koromo-copy/releases/download/1.7.6985.22934/Koromo.Copy.exe 이 파일만 놔둔 채로 실행해주세요
정상적으로 실행된다면 히토미 카피의 다운로드 기록 파일인 log.json도 새로운 폴더에 넣으면 됩니다

히토미 카피하고 Koromo Copy의 데이터들은 log.json을 제외하고는 호환이 안되요

**Comment by SC1100** [comment]
덕분에 해결했습니다 항상 잘 쓰고있어요 감사합니다

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2019년 2월 18일 (월) 오후 5:26, koromo <notifications@github.com>님이 작성:
