### ISSUE TITLE
다운된 폴더 내부의 이미지파일 넘버링에 관해서 도움 부탁 드려도 될까요

### ISSUE THREAD

**Issue by SC1100** [dc-koromo/koromo-copy#6]
이전 히토미카피를 쓰다가 넘어왔었는데 다운받은 폴더 내부에 이미지파일 넘버링이 히토미카피는 '1' '2' 이런식이었는데 코로모카피는 '001' '002' 이런식이라 중복파일들이 너무 생기는데 어떻게 해야 넘버링 설정을 수정 할 수 있나요 setting.json 을 열어봐도 해당 설정을 못찾겠어요 도움 부탁드려도 될까요?

**Comment by dc-koromo** [comment]
파일 넘버링은 프로그램상에서 구현되어있어 현재는 변경할 수 있는 방법이 없어요
추후에 추가할께요
그리고, 중복파일이 생긴다는게 정확히 무슨 말인지 알 수 있을까요?

**Comment by SC1100** [comment]
중복파일은 그냥 제가 히토미카피에서 다운받았던걸 코로모카피로 또 받아서 그런거에요 파일 덮어쓰기 했을때 안에 이름이 조금 다른 같은 이미지파일이 추가된다는 거였어요 말을 너무 생략해서 했네요 피드백 감사합니다
