### ISSUE TITLE
언어 설정이 반영되지 않습니다.

### ISSUE THREAD

**Issue by affinityDrops** [dc-koromo/koromo-copy#8]
어느 언어를 선택해도 모든 언어가 검색되는 것처럼 보입니다.
자동완성으로 나타나는 총 개수는 제대로 표시되는 것 같습니다.

**Comment by dc-koromo** [comment]
Ctrl + T를 눌러
```
internal --get settings.Model.Hitomi.Language
```
명령을 실행하고, 설정된 언어가 제대로 출력되는지 확인해 주세요.

고급 검색이 켜져있는 경우엔 '고급검색시 설정된 언어를 항상 검색어로 추가' 옵션에 따라 검색언어 설정이 바뀔 수 있습니다.
이 경우엔 위 옵션을 끄고 검색을 해주세요.

**Comment by affinityDrops** [comment]
답변 감사합니다. 해결 됐습니다.
